# Generated by Django 2.0.1 on 2018-08-10 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LQReel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reel_no', models.SmallIntegerField(verbose_name='卷序号')),
                ('start_vol', models.SmallIntegerField(verbose_name='起始册')),
                ('start_vol_page', models.SmallIntegerField(verbose_name='起始页码')),
                ('end_vol', models.SmallIntegerField(verbose_name='终止册')),
                ('end_vol_page', models.SmallIntegerField(verbose_name='终止页码')),
                ('is_existed', models.BooleanField(default=True, verbose_name='卷是否存在')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_lqreel_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '龙泉藏经卷',
                'verbose_name_plural': '龙泉藏经卷',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LQSutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sid', models.CharField(max_length=8, unique=True, verbose_name='龙泉经号')),
                ('code', models.CharField(max_length=5, verbose_name='龙泉经目编码')),
                ('variant_code', models.CharField(default='0', max_length=1, verbose_name='别本号')),
                ('name', models.CharField(max_length=64, verbose_name='龙泉经名')),
                ('total_reels', models.IntegerField(blank=True, default=1, verbose_name='总卷数')),
                ('cur_reels', models.IntegerField(blank=True, default=1, verbose_name='实际卷数')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='著译者')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_lqsutra_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_lqsutra_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '龙泉经目',
                'verbose_name_plural': '龙泉经目',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pid', models.CharField(blank=True, max_length=21, null=True, verbose_name='实体藏经页级总编码')),
                ('page_code', models.CharField(max_length=23, verbose_name='页代码')),
                ('reel_page_no', models.SmallIntegerField(blank=True, null=True, verbose_name='卷中页序号')),
                ('volume_page_no', models.SmallIntegerField(verbose_name='页序号')),
                ('is_existed', models.BooleanField(default=True, verbose_name='页是否存在')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_page_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '实体藏经页',
                'verbose_name_plural': '实体藏经页',
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reel_no', models.SmallIntegerField(verbose_name='卷序号')),
                ('start_vol', models.SmallIntegerField(verbose_name='起始册')),
                ('start_vol_page', models.SmallIntegerField(verbose_name='起始页码')),
                ('end_vol', models.SmallIntegerField(verbose_name='终止册')),
                ('end_vol_page', models.SmallIntegerField(verbose_name='终止页码')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_reel_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '实体卷',
                'verbose_name_plural': '实体卷',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sid', models.CharField(max_length=8, unique=True, verbose_name='经编码')),
                ('code', models.CharField(max_length=5, verbose_name='实体经目编码')),
                ('variant_code', models.CharField(default='0', max_length=1, verbose_name='别本编码')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='经名')),
                ('total_reels', models.IntegerField(blank=True, default=1, verbose_name='总卷数')),
                ('cur_reels', models.IntegerField(blank=True, default=1, verbose_name='实际卷数')),
                ('author', models.CharField(blank=True, default='', max_length=32, verbose_name='作译者')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_sutra_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lqsutra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsdata.LQSutra', verbose_name='龙泉经目编码')),
            ],
            options={
                'verbose_name': '实体经',
                'verbose_name_plural': '实体经',
            },
        ),
        migrations.CreateModel(
            name='Tripitaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=32, verbose_name='藏名')),
                ('shortname', models.CharField(max_length=32, verbose_name='简称（用于校勘记）')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_tripitaka_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_tripitaka_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '实体藏',
                'verbose_name_plural': '实体藏',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vol_no', models.SmallIntegerField(verbose_name='册序号')),
                ('total_pages', models.IntegerField(verbose_name='册页数')),
                ('cur_pages', models.IntegerField(verbose_name='实际页数')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_volume_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tripitaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Tripitaka', verbose_name='藏名')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_volume_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '实体册',
                'verbose_name_plural': '实体册',
            },
        ),
        migrations.AddField(
            model_name='sutra',
            name='tripitaka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Tripitaka', verbose_name='藏名'),
        ),
        migrations.AddField(
            model_name='sutra',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_sutra_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='reel',
            name='sutra',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Sutra', verbose_name='实体经'),
        ),
        migrations.AddField(
            model_name='reel',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_reel_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='page',
            name='reel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Reel', verbose_name='实体藏经卷'),
        ),
        migrations.AddField(
            model_name='page',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_page_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Volume', verbose_name='实体藏经册'),
        ),
        migrations.AddField(
            model_name='lqreel',
            name='lqsutra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.LQSutra', verbose_name='龙泉经目编码'),
        ),
        migrations.AddField(
            model_name='lqreel',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsdata_lqreel_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('tripitaka', 'vol_no')},
        ),
        migrations.AlterUniqueTogether(
            name='reel',
            unique_together={('sutra', 'reel_no')},
        ),
        migrations.AlterUniqueTogether(
            name='lqreel',
            unique_together={('lqsutra', 'reel_no')},
        ),
    ]
