# Generated by Django 2.0.1 on 2018-08-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='is_exist',
            new_name='is_existed',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_no',
            new_name='volume_page_no',
        ),
    ]
