# Generated by Django 2.0.1 on 2018-08-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0002_auto_20180805_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Page2',
        ),
    ]
