# Generated by Django 2.0.1 on 2018-08-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0003_auto_20180805_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page2',
            new_name='Page',
        ),
    ]
