# Generated by Django 2.0.2 on 2018-08-07 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tsdata', '0004_auto_20180805_1110'),
    ]

    operations = [                
       
       
    ]
