# Generated by Django 2.0.1 on 2018-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0008_auto_20180807_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lqsutra',
            options={'verbose_name': '龙泉经', 'verbose_name_plural': '龙泉经'},
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='sid',
            field=models.CharField(max_length=8, verbose_name='龙泉经号'),
        ),
    ]
