# Generated by Django 2.0.2 on 2018-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretask', '0002_auto_20180630_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepagecoltask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='prepagecoltask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='prepagecolverifytask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='prepagecolverifytask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
    ]
