# Generated by Django 2.0.2 on 2018-04-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetask',
            name='redo_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='任务重作数'),
        ),
    ]
