# Generated by Django 2.0.2 on 2018-04-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_pagetask_redo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerect',
            name='pptask_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='当前任务数'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'cut_ready': False, 'image_ready': True}, to='tdata.Reel'),
        ),
    ]
