# Generated by Django 2.0.2 on 2018-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0004_pagetask_pagerect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetask',
            name='current_x',
            field=models.IntegerField(default=0, verbose_name='当前块X坐标'),
        ),
        migrations.AddField(
            model_name='pagetask',
            name='current_y',
            field=models.IntegerField(default=0, verbose_name='当前块Y坐标'),
        ),
    ]
