# Generated by Django 2.0.2 on 2018-06-06 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tdata.lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rect', '0005_auto_20180604_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVerifyTask',
            fields=[
                ('number', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('ttype', models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='任务格式化描述')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '低'), (3, '中'), (5, '高'), (7, '最高')], db_index=True, default=3, verbose_name='任务优先级')),
                ('update_date', models.DateField(null=True, verbose_name='最近处理时间')),
                ('obtain_date', models.DateField(null=True, verbose_name='领取时间')),
                ('count', models.IntegerField(default=1, verbose_name='任务页的数量')),
                ('current_x', models.IntegerField(default=0, verbose_name='当前块X坐标')),
                ('current_y', models.IntegerField(default=0, verbose_name='当前块Y坐标')),
                ('page_set', tdata.lib.fields.JSONField(default=list, verbose_name='页的集合')),
                ('redo_count', models.PositiveSmallIntegerField(default=1, verbose_name='任务重作数')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageverity_tasks', to=settings.AUTH_USER_MODEL)),
                ('pagerect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rect.PageRect')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageverity_tasks', to='rect.Schedule', verbose_name='切分计划')),
            ],
            options={
                'verbose_name': '切分校对审定',
                'verbose_name_plural': '切分校对审定',
            },
        ),
        migrations.AlterModelOptions(
            name='pagetask',
            options={'verbose_name': '切分校对', 'verbose_name_plural': '切分校对'},
        ),
    ]
