# Generated by Django 2.0.2 on 2018-06-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0006_auto_20180606_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='verifier',
        ),
        migrations.DeleteModel(
            name='Patch',
        ),
    ]
