# Generated by Django 2.0.2 on 2018-07-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0007_auto_20180606_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenttask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='absenttask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='absenttask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_tasks', to=settings.AUTH_USER_MODEL, verbose_name='领取用户'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageverity_tasks', to=settings.AUTH_USER_MODEL, verbose_name='领取用户'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='obtain_date',
            field=models.DateTimeField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '进行中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='最近处理时间'),
        ),
    ]
