# Generated by Django 2.0.2 on 2018-07-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0008_auto_20180715_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenttask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='absenttask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='pageverifytask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='obtain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近处理时间'),
        ),
    ]
