# Generated by Django 2.0.2 on 2018-04-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lqreel',
            options={'ordering': ('id',), 'verbose_name': '龙泉藏经卷', 'verbose_name_plural': '龙泉藏经卷'},
        ),
    ]
