# Generated by Django 2.0.2 on 2018-04-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0002_auto_20180408_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='edition_type',
        ),
        migrations.AddField(
            model_name='lqreel',
            name='text_ready',
            field=models.BooleanField(default=False, verbose_name='是否有龙泉藏经经文'),
        ),
    ]
