# Generated by Django 2.0.2 on 2018-04-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0003_auto_20180414_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ('id',), 'verbose_name': '实体卷', 'verbose_name_plural': '实体卷'},
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_end_char_no',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_end_line_no',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_end_page',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_start_char_no',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_start_line_no',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_start_page',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='f_text',
        ),
        migrations.RemoveField(
            model_name='reelocrtext',
            name='fixed',
        ),
    ]
