# Generated by Django 2.0.2 on 2018-05-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0004_auto_20180426_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Page', verbose_name='实体藏经页'),
        ),
        migrations.AlterField(
            model_name='lqreel',
            name='lqsutra',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQSutra', verbose_name='龙泉经目编码'),
        ),
        migrations.AlterField(
            model_name='page',
            name='reel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Reel', verbose_name='实体藏经卷'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='sutra',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Sutra', verbose_name='实体藏经'),
        ),
        migrations.AlterField(
            model_name='reelocrtext',
            name='reel',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tdata.Reel', verbose_name='实体藏经卷'),
        ),
    ]
