# Generated by Django 2.0.2 on 2018-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0005_auto_20180513_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='task_timeout',
            field=models.IntegerField(default=604800, verbose_name='校勘任务自动回收时间（秒）'),
        ),
    ]
