# Generated by Django 2.0.5 on 2018-05-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0007_tripitaka_bar_line_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='used_in_collation',
            field=models.BooleanField(default=True, verbose_name='是否用于校勘'),
        ),
    ]
