# Generated by Django 2.0.5 on 2018-06-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0008_reel_used_in_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitaka',
            name='use_original_cut',
            field=models.BooleanField(default=False, verbose_name='使用原始切分'),
        ),
    ]
