# Generated by Django 2.0.5 on 2018-06-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0009_tripitaka_use_original_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='mark_ready',
            field=models.BooleanField(default=False, verbose_name='是否完成格式标注'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('tripitaka', 'vol_no')},
        ),
    ]
