# Generated by Django 2.0.2 on 2018-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0009_auto_20180531_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitaka',
            name='bar_line_count',
            field=models.CharField(default='0', max_length=256, verbose_name='每栏文本行数'),
        ),
    ]
