# Generated by Django 2.0.2 on 2018-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0010_auto_20180531_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='bar_line_count',
            field=models.CharField(default='0', max_length=256, verbose_name='每栏文本行数'),
        ),
    ]
