# Generated by Django 2.0.5 on 2018-06-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0010_auto_20180605_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelInfo',
            fields=[
            ],
            options={
                'verbose_name': '实体卷',
                'verbose_name_plural': '实体卷',
                'proxy': True,
                'indexes': [],
            },
            bases=('tdata.reel',),
        ),
        migrations.CreateModel(
            name='ReelTaskProgress',
            fields=[
            ],
            options={
                'verbose_name': '实体卷任务进度',
                'verbose_name_plural': '实体卷任务进度',
                'proxy': True,
                'indexes': [],
            },
            bases=('tdata.reel',),
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_1',
            field=models.NullBooleanField(verbose_name='文字校对校一'),
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_2',
            field=models.NullBooleanField(verbose_name='文字校对校二'),
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_3',
            field=models.NullBooleanField(verbose_name='文字校对校三'),
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_4',
            field=models.NullBooleanField(verbose_name='文字校对校四'),
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_difficult',
            field=models.NullBooleanField(verbose_name='文字校对难字处理'),
        ),
        migrations.AddField(
            model_name='reel',
            name='correct_verify',
            field=models.NullBooleanField(verbose_name='文字校对审定'),
        ),
        migrations.AddField(
            model_name='reel',
            name='finished_cut_count',
            field=models.SmallIntegerField(default=0, verbose_name='切分完成的页数'),
        ),
        migrations.AddField(
            model_name='reel',
            name='mark_1',
            field=models.NullBooleanField(verbose_name='格式标注一'),
        ),
        migrations.AddField(
            model_name='reel',
            name='mark_2',
            field=models.NullBooleanField(verbose_name='格式标注二'),
        ),
        migrations.AddField(
            model_name='reel',
            name='mark_verify',
            field=models.NullBooleanField(verbose_name='格式标注审定'),
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='name',
            field=models.CharField(max_length=64, verbose_name='龙泉经名'),
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='sid',
            field=models.CharField(max_length=8, unique=True, verbose_name='龙泉经号'),
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='variant_code',
            field=models.CharField(default='0', max_length=1, verbose_name='别本号'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='end_vol_page',
            field=models.SmallIntegerField(verbose_name='终止页码'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='start_vol_page',
            field=models.SmallIntegerField(verbose_name='起始页码'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='sutra',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Sutra', verbose_name='实体经'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='经名'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='sid',
            field=models.CharField(max_length=8, unique=True, verbose_name='经编码'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='tripitaka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdata.Tripitaka', verbose_name='藏名'),
        ),
        migrations.AlterField(
            model_name='tripitaka',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='tripitaka',
            name='name',
            field=models.CharField(max_length=32, verbose_name='藏名'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='tripitaka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdata.Tripitaka', verbose_name='藏名'),
        ),
    ]
