# Generated by Django 2.0.2 on 2018-06-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0011_reel_bar_line_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelocrtext',
            old_name='reel',
            new_name='reel_id',
        ),
    ]
