# Generated by Django 2.0.2 on 2018-06-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0011_auto_20180615_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifycode',
        ),
    ]
