# Generated by Django 2.0.5 on 2018-06-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0012_remove_reel_bar_line_count'),
        ('tdata', '0011_auto_20180621_1547'),
    ]

    operations = [
    ]
