# Generated by Django 2.0.2 on 2018-06-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0012_auto_20180608_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelocrtext',
            old_name='reel_id',
            new_name='reel',
        ),
    ]
