# Generated by Django 2.0.5 on 2018-07-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0013_merge_20180622_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
