# Generated by Django 2.0.2 on 2018-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdata', '0014_emailverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifycode',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='用户名'),
        ),
    ]
