# Generated by Django 2.0.1 on 2018-08-10 01:22

from django.db import migrations, models
import django.db.models.deletion
import tdata.lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=23)),
                ('char', models.CharField(max_length=2)),
                ('similarity', models.FloatField(blank=True, default=1, null=True, verbose_name='相似度')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('x', models.SmallIntegerField(default=0, verbose_name='X坐标')),
                ('y', models.SmallIntegerField(default=0, verbose_name='Y坐标')),
                ('x1', models.SmallIntegerField(default=0, verbose_name='X1坐标')),
                ('y1', models.SmallIntegerField(default=0, verbose_name='Y1坐标')),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Page', verbose_name='实体藏经页')),
                ('reel', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Reel', verbose_name='实体藏经卷')),
                ('sutra', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Sutra', verbose_name='实体经')),
                ('tripitaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Tripitaka', verbose_name='藏名')),
            ],
            options={
                'verbose_name': '列切分数据',
                'verbose_name_plural': '列切分数据',
            },
        ),
        migrations.CreateModel(
            name='data_column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_code', models.CharField(max_length=23)),
                ('column_no', models.CharField(max_length=23)),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('x', models.SmallIntegerField(default=0, verbose_name='X坐标')),
                ('y', models.SmallIntegerField(default=0, verbose_name='Y坐标')),
                ('x1', models.SmallIntegerField(default=0, verbose_name='X1坐标')),
                ('y1', models.SmallIntegerField(default=0, verbose_name='Y1坐标')),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Page', verbose_name='实体藏经页')),
            ],
            options={
                'verbose_name': '列切分数据',
                'verbose_name_plural': '列切分数据',
            },
        ),
        migrations.CreateModel(
            name='data_lqreel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collate_txt', models.TextField(blank=True, default='', verbose_name='校对文本')),
                ('punct_txt', models.TextField(blank=True, default='', verbose_name='标点文本')),
                ('base_reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Reel', verbose_name='底本卷')),
                ('lqreel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.LQReel', verbose_name='龙泉经卷')),
            ],
            options={
                'verbose_name': '龙泉卷经文',
                'verbose_name_plural': '龙泉卷经文',
            },
        ),
        migrations.CreateModel(
            name='data_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, default='', verbose_name='经文')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('ocr_char_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='文字切分')),
                ('ocr_col_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='列切分')),
                ('ocr_block_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='区块切分')),
                ('ocr_txt', models.TextField(blank=True, default='', verbose_name='ocr识别文字')),
                ('confirm_char_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='确认文字切分')),
                ('confirm_col_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='确认列切分')),
                ('confirm_block_cut', tdata.lib.fields.JSONField(default=dict, verbose_name='确认区块切分')),
                ('confirm_txt', models.TextField(blank=True, default='', verbose_name='确认ocr识别文字')),
                ('mark_txt', models.TextField(blank=True, default='', verbose_name='格式标注文本')),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tsdata.Page', verbose_name='实体藏经页')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Reel', verbose_name='龙泉经卷')),
            ],
            options={
                'verbose_name': '实体经页数据',
                'verbose_name_plural': '实体经页数据',
            },
        ),
        migrations.CreateModel(
            name='data_reel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, default='', verbose_name='经文')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Reel', verbose_name='龙泉经卷')),
            ],
            options={
                'verbose_name': '实体卷经文',
                'verbose_name_plural': '实体卷经文',
            },
        ),
        migrations.CreateModel(
            name='data_tripitaka_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_description', models.CharField(max_length=255, verbose_name='存储描述')),
                ('tripitaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdata.Tripitaka', verbose_name='藏名')),
            ],
            options={
                'verbose_name': '实体藏描述',
                'verbose_name_plural': '实体藏描述',
            },
        ),
    ]
