# Generated by Django 2.0.1 on 2018-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsbdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_char',
            name='similarity',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='相似度'),
        ),
    ]
