# Generated by Django 2.0.2 on 2018-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180330_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未就绪'), (2, '待领取'), (3, '进行中'), (5, '已暂停'), (4, '已完成'), (6, '已催单'), (7, '已回收'), (8, '系统内暂停')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
