# Generated by Django 2.0.2 on 2018-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180408_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctseg',
            name='text3',
            field=models.TextField(blank=True, null=True, verbose_name='文本3'),
        ),
        migrations.AddField(
            model_name='correctseg',
            name='text4',
            field=models.TextField(blank=True, null=True, verbose_name='文本4'),
        ),
        migrations.AlterField(
            model_name='correctseg',
            name='selected_text',
            field=models.TextField(blank=True, null=True, verbose_name='修正文本'),
        ),
        migrations.AlterField(
            model_name='correctseg',
            name='text1',
            field=models.TextField(blank=True, null=True, verbose_name='文本1'),
        ),
        migrations.AlterField(
            model_name='correctseg',
            name='text2',
            field=models.TextField(blank=True, null=True, verbose_name='文本2'),
        ),
    ]
