# Generated by Django 2.0.2 on 2018-04-20 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_remove_diffseg_diffseg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(blank=True, default='', null=True, verbose_name='原始文本')),
                ('fb_text', models.TextField(blank=True, default='', null=True, verbose_name='反馈文本')),
                ('fb_comment', models.TextField(verbose_name='反馈说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='反馈时间')),
                ('processed_at', models.DateTimeField(null=True, verbose_name='审查时间')),
                ('response', models.SmallIntegerField(choices=[(1, '未处理'), (2, '同意'), (3, '不同意')], default=1, verbose_name='审查意见')),
                ('position', models.IntegerField(default=0, verbose_name='在卷文本中的位置（前有几个字）')),
                ('correct_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelCorrectText')),
                ('fb_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_correctfeedback', to=settings.AUTH_USER_MODEL, verbose_name='审查用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JudgeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(blank=True, default='', null=True, verbose_name='原始文本')),
                ('fb_text', models.TextField(blank=True, default='', null=True, verbose_name='反馈文本')),
                ('fb_comment', models.TextField(verbose_name='反馈说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='反馈时间')),
                ('processed_at', models.DateTimeField(null=True, verbose_name='审查时间')),
                ('response', models.SmallIntegerField(choices=[(1, '未处理'), (2, '同意'), (3, '不同意')], default=1, verbose_name='审查意见')),
                ('diffsegresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tasks.DiffSegResult')),
                ('fb_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_judgefeedback', to=settings.AUTH_USER_MODEL, verbose_name='审查用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='correctdoubt',
            name='correct_seg',
        ),
        migrations.RemoveField(
            model_name='correctdoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='correctdoubt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='judgedoubt',
            name='diffseg',
        ),
        migrations.RemoveField(
            model_name='judgedoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='judgedoubt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lqmark',
            name='lqreel',
        ),
        migrations.RemoveField(
            model_name='lqmark',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='lqmark',
            name='reeltext',
        ),
        migrations.RemoveField(
            model_name='lqmark',
            name='task',
        ),
        migrations.RemoveField(
            model_name='lqmarkdoubt',
            name='lqmarkunit',
        ),
        migrations.RemoveField(
            model_name='lqmarkdoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='lqmarkdoubt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lqmarkunit',
            name='lqmark',
        ),
        migrations.RemoveField(
            model_name='lqpunctdoubt',
            name='lqreel',
        ),
        migrations.RemoveField(
            model_name='lqpunctdoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='lqpunctdoubt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='markdoubt',
            name='markunit',
        ),
        migrations.RemoveField(
            model_name='markdoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='markdoubt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='punctdoubt',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='punctdoubt',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='punctdoubt',
            name='user',
        ),
        migrations.DeleteModel(
            name='CorrectDoubt',
        ),
        migrations.DeleteModel(
            name='JudgeDoubt',
        ),
        migrations.DeleteModel(
            name='LQMark',
        ),
        migrations.DeleteModel(
            name='LQMarkDoubt',
        ),
        migrations.DeleteModel(
            name='LQMarkUnit',
        ),
        migrations.DeleteModel(
            name='LQPunctDoubt',
        ),
        migrations.DeleteModel(
            name='MarkDoubt',
        ),
        migrations.DeleteModel(
            name='PunctDoubt',
        ),
    ]
