# Generated by Django 2.0.2 on 2018-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180420_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgefeedback',
            options={'verbose_name': '校勘反馈', 'verbose_name_plural': '校勘反馈'},
        ),
        migrations.AddField(
            model_name='doubtseg',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='是否处理'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_no',
            field=models.SmallIntegerField(choices=[(0, '无序号'), (1, '一'), (2, '二'), (3, '三'), (4, '四')], default=0, verbose_name='组合任务序号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='typ',
            field=models.SmallIntegerField(choices=[(1, '文字校对'), (2, '文字校对审定'), (3, '校勘判取'), (4, '校勘判取审定'), (5, '基础标点'), (6, '基础标点审定'), (7, '定本标点'), (8, '定本标点审定'), (9, '格式标注'), (10, '格式标注审定'), (11, '文字校对难字处理'), (12, '校勘判取难字处理')], db_index=True, verbose_name='任务类型'),
        ),
    ]
