# Generated by Django 2.0.2 on 2018-04-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_auto_20180422_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='LQPunctFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0, verbose_name='起始字index')),
                ('end', models.IntegerField(default=0, verbose_name='结束字下一个index')),
                ('fb_punctuation', models.TextField(blank=True, null=True, verbose_name='反馈标点')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='反馈时间')),
                ('status', models.SmallIntegerField(choices=[(2, '待领取'), (3, '进行中'), (4, '已完成')], db_index=True, default=2, verbose_name='状态')),
                ('punctuation', models.TextField(blank=True, null=True, verbose_name='审查标点')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='审查时间')),
                ('fb_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
                ('lqpunct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.LQPunct', verbose_name='定本标点')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_lqpunctfeedback', to=settings.AUTH_USER_MODEL, verbose_name='审查用户')),
            ],
            options={
                'verbose_name': '定本标点反馈',
                'verbose_name_plural': '定本标点反馈',
            },
        ),
        migrations.AlterModelOptions(
            name='correctfeedback',
            options={'verbose_name': '文字校对反馈', 'verbose_name_plural': '文字校对反馈'},
        ),
    ]
