# Generated by Django 2.0.2 on 2018-05-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180430_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelcorrecttext',
            name='reel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reel_correct_texts', to='tdata.Reel', verbose_name='实体藏经卷'),
        ),
        migrations.AlterField(
            model_name='reeldiff',
            name='lqsutra',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQSutra'),
        ),
        migrations.AlterField(
            model_name='task',
            name='base_reel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.Reel', verbose_name='底本'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lqreel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQReel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lqtext',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lqpunct_tasks', to='tasks.LQReelText', verbose_name='龙泉藏经卷经文'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tdata.Reel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reeldiff',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ReelDiff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reeltext',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punct_tasks', to='tasks.ReelCorrectText'),
        ),
    ]
