# Generated by Django 2.0.2 on 2018-05-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180430_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='markunit',
            name='mark_typ',
            field=models.SmallIntegerField(default=1, verbose_name='标注类型'),
        ),
        migrations.AlterField(
            model_name='diffsegresult',
            name='selected_text',
            field=models.TextField(blank=True, null=True, verbose_name='判取文本'),
        ),
        migrations.AlterField(
            model_name='markunit',
            name='typ',
            field=models.SmallIntegerField(choices=[(1, '标注'), (2, '确认标注'), (3, '标注差异'), (4, '标注反馈')], default=1, verbose_name='类型'),
        ),
    ]
