# Generated by Django 2.0.2 on 2018-05-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180512_1539'),
        ('tasks', '0009_auto_20180513_1506'),
    ]

    operations = [
    ]
