# Generated by Django 2.0.2 on 2018-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_merge_20180521_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markunit',
            name='typ',
            field=models.SmallIntegerField(choices=[(1, '标注'), (2, '存疑标注'), (3, '标注反馈')], default=1, verbose_name='类型'),
        ),
    ]
