# Generated by Django 2.0.5 on 2018-06-06 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180522_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtask',
            options={'verbose_name': '批次任务', 'verbose_name_plural': '批次任务'},
        ),
        migrations.AlterField(
            model_name='mark',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='markunit',
            name='mark_typ',
            field=models.SmallIntegerField(choices=[(1, '标题'), (2, '作译者'), (3, '序'), (4, '千字文'), (5, '跋'), (6, '行间小字'), (11, '偈颂'), (12, '夹注小字'), (13, '梵文'), (14, '咒语')], default=1, verbose_name='标注类型'),
        ),
    ]
