# Generated by Django 2.0.2 on 2018-06-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20180606_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='reeltext',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelCorrectText', verbose_name='实体藏经卷经文'),
        ),
    ]
