# Generated by Django 2.0.2 on 2018-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20180615_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectDifficultTask',
            fields=[
            ],
            options={
                'verbose_name': '文字校对难字',
                'verbose_name_plural': '文字校对难字',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='CorrectTask',
            fields=[
            ],
            options={
                'verbose_name': '文字校对',
                'verbose_name_plural': '文字校对',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='CorrectVerifyTask',
            fields=[
            ],
            options={
                'verbose_name': '文字校对审定',
                'verbose_name_plural': '文字校对审定',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='JudgeDifficultTask',
            fields=[
            ],
            options={
                'verbose_name': '校勘判取难字',
                'verbose_name_plural': '校勘判取难字',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='JudgeTask',
            fields=[
            ],
            options={
                'verbose_name': '校勘判取',
                'verbose_name_plural': '校勘判取',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='JudgeVerifyTask',
            fields=[
            ],
            options={
                'verbose_name': '校勘判取审定',
                'verbose_name_plural': '校勘判取审定',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='LQPunctTask',
            fields=[
            ],
            options={
                'verbose_name': '定本标点',
                'verbose_name_plural': '定本标点',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='LQPunctVerifyTask',
            fields=[
            ],
            options={
                'verbose_name': '定本标点审定',
                'verbose_name_plural': '定本标点审定',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='MarkTask',
            fields=[
            ],
            options={
                'verbose_name': '格式标注',
                'verbose_name_plural': '格式标注',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='MarkVerifyTask',
            fields=[
            ],
            options={
                'verbose_name': '格式标注审定',
                'verbose_name_plural': '格式标注审定',
                'proxy': True,
                'indexes': [],
            },
            bases=('tasks.task',),
        ),
        migrations.AlterModelOptions(
            name='batchtask',
            options={'verbose_name': '任务批次', 'verbose_name_plural': '任务批次'},
        ),
        migrations.AlterField(
            model_name='task',
            name='typ',
            field=models.SmallIntegerField(choices=[(1, '文字校对'), (2, '文字校对审定'), (3, '校勘判取'), (4, '校勘判取审定'), (7, '定本标点'), (8, '定本标点审定'), (9, '格式标注'), (10, '格式标注审定'), (11, '文字校对难字处理'), (12, '校勘判取难字处理')], db_index=True, verbose_name='任务类型'),
        ),
    ]
