# Generated by Django 2.0.2 on 2018-06-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20180618_1522'),
        ('tasks', '0013_auto_20180615_1810'),
    ]

    operations = [
    ]
