# Generated by Django 2.0.5 on 2018-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20180715_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='代码')),
                ('key', models.CharField(max_length=256, verbose_name='名称')),
                ('value', models.TextField(verbose_name='值')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
